use-cases/model-fine-tuning-pipeline/model-eval/README.md
use-cases/model-fine-tuning-pipeline/model-eval/manifests/deployment-a100.yaml
use-cases/model-fine-tuning-pipeline/model-eval/manifests/deployment-l4.yaml

- Add accelerator suffix to readme instructions on the wait
- Add GCS Fuse parallel download attributes

fix accelerator for wait and add gcsfuse parallel downloads

---

use-cases/model-fine-tuning-pipeline/fine-tuning/pytorch/README.md
use-cases/model-fine-tuning-pipeline/fine-tuning/pytorch/manifests/fine-tune-a100-dws.yaml
use-cases/model-fine-tuning-pipeline/fine-tuning/pytorch/manifests/fine-tune-h100-dws.yaml
use-cases/model-fine-tuning-pipeline/fine-tuning/pytorch/manifests/fine-tune-l4-dws.yaml

Environment variable TRAIN_BATCH_SIZE setting for fine-tuning job, default to 1

add env var TRAIN_BATCH_SIZE for training flexibility

---

terraform/features/nim/README.md
terraform/features/nim/main.tf
terraform/features/nim/providers.tf
terraform/features/nim/variables.tf
terraform/features/nim/versions.tf

This PR add deployment of Meta's llama3 with NVIDIA NIM

feat: add nim deployment as a feature

---

docs/use-cases/model-fine-tuning-pipeline/README.md
use-cases/model-fine-tuning-pipeline/data-preparation/gemma-it/README.md
use-cases/model-fine-tuning-pipeline/data-processing/ray/README.md

Add cc license reference for docs and how-to

add cc license for dataset

---

use-cases/rag-pipeline/multimodal-emb/src/Dockerfile
use-cases/rag-pipeline/rag-on-gke/embedding-models/multimodal-embedding/manifests/embedding.yaml
use-cases/rag-pipeline/rag-on-gke/embedding-models/multimodal-embedding/src/Dockerfile
use-cases/rag-pipeline/rag-on-gke/embedding-models/multimodal-embedding/src/requirements.txt

Small PR to fix multimodal embeddings Docker image as well as service and deployment naming conventions

Fixes multimodal image

---

use-cases/model-fine-tuning-pipeline/data-preparation/gemma-it/README.md
use-cases/model-fine-tuning-pipeline/data-processing/ray/README.md
use-cases/model-fine-tuning-pipeline/fine-tuning/pytorch/README.md
use-cases/model-fine-tuning-pipeline/model-eval/README.md
use-cases/model-fine-tuning-pipeline/model-eval/manifests/transfer-to-gcs.yaml

- Instructions to download processed data
- Validate user `HF_TOKEN` and Gemma model agreement

Instructions to use processed data and models, along with respective subset data

---

use-cases/inferencing/batch-inference/README.md
use-cases/inferencing/benchmark/README.md
use-cases/inferencing/benchmark/manifests/locust-master-controller.yaml
use-cases/inferencing/serving/vllm/README.md
use-cases/inferencing/serving/vllm/autoscaling/README.md
use-cases/inferencing/serving/vllm/gcsfuse/README.md
use-cases/inferencing/serving/vllm/gcsfuse/manifests/gradio.yaml
use-cases/inferencing/serving/vllm/hyperdisk-ml/README.md
use-cases/inferencing/serving/vllm/hyperdisk-ml/manifests/gradio.yaml
use-cases/inferencing/serving/vllm/hyperdisk-ml/manifests/model-deployment-a100.yaml
use-cases/inferencing/serving/vllm/hyperdisk-ml/manifests/model-deployment-h100.yaml
use-cases/inferencing/serving/vllm/hyperdisk-ml/manifests/model-deployment-l4.yaml
use-cases/inferencing/serving/vllm/hyperdisk-ml/manifests/volume-prep/job.yaml
use-cases/inferencing/serving/vllm/metrics/README.md
use-cases/inferencing/serving/vllm/persistent-disk/README.md
use-cases/inferencing/serving/vllm/persistent-disk/manifests/gradio.yaml
use-cases/inferencing/serving/vllm/persistent-disk/manifests/model-deployment-a100.yaml
use-cases/inferencing/serving/vllm/persistent-disk/manifests/model-deployment-h100.yaml
use-cases/inferencing/serving/vllm/persistent-disk/manifests/model-deployment-l4.yaml
use-cases/inferencing/serving/vllm/persistent-disk/manifests/volume-prep/job.yaml

Links to the updated guides:
- [Distributed Inferencing on vLLM](https://github.com/GoogleCloudPlatform/accelerated-platforms/blob/rueth-inferencing/use-cases/inferencing/serving/vllm/README.md)
- [Distributed Inferencing on vLLM using Persistent disk](https://github.com/GoogleCloudPlatform/accelerated-platforms/blob/rueth-inferencing/use-cases/inferencing/serving/vllm/persistent-disk/README.md)
- [vLLM Metrics](https://github.com/GoogleCloudPlatform/accelerated-platforms/blob/rueth-inferencing/use-cases/inferencing/serving/vllm/metrics/README.md)
- [vLLM autoscaling with horizontal pod autoscaling (HPA)](https://github.com/GoogleCloudPlatform/accelerated-platforms/blob/rueth-inferencing/use-cases/inferencing/serving/vllm/autoscaling/README.md)
- [Benchmarking with …

Updates based on initial review

---

use-cases/inferencing/batch-inference/README.md
use-cases/inferencing/batch-inference/src/.gcloudignore
use-cases/inferencing/batch-inference/src/logging.conf
use-cases/inferencing/batch-inference/src/run_batch_predictions.py
use-cases/inferencing/benchmark/README.md
use-cases/inferencing/benchmark/src/logging.conf
use-cases/inferencing/serving/vllm/README.md
use-cases/inferencing/serving/vllm/autoscaling/README.md
use-cases/inferencing/serving/vllm/gcsfuse/README.md
use-cases/inferencing/serving/vllm/gcsfuse/manifests/gradio.yaml
use-cases/inferencing/serving/vllm/hyperdisk-ml/README.md
use-cases/inferencing/serving/vllm/hyperdisk-ml/manifests/gradio.yaml
use-cases/inferencing/serving/vllm/hyperdisk-ml/manifests/volume-prep/downloads-persistent-volume-claim.yaml
use-cases/inferencing/serving/vllm/hyperdisk-ml/manifests/volume-prep/job.yaml
use-cases/inferencing/serving/vllm/metrics/README.md
use-cases/inferencing/serving/vllm/persistent-disk/README.md
use-cases/inferencing/serving/vllm/persistent-disk/manifests/model-deployment-a100.yaml
use-cases/inferencing/serving/vllm/persistent-disk/manifests/model-deployment-h100.yaml
use-cases/inferencing/serving/vllm/persistent-disk/manifests/model-deployment-l4.yaml
use-cases/inferencing/serving/vllm/persistent-disk/manifests/volume-prep/downloads-persistent-volume-claim.yaml
use-cases/inferencing/serving/vllm/persistent-disk/manifests/volume-prep/job.yaml
use-cases/inferencing/serving/vllm/persistent-disk/manifests/volume-prep/persistent-volume-claim.yaml
use-cases/inferencing/serving/vllm/persistent-disk/manifests/volume-prep/persistent-volume.yaml

Links to the updated guides:
- [Distributed Inferencing on vLLM](https://github.com/GoogleCloudPlatform/accelerated-platforms/blob/rueth-inferencing/use-cases/inferencing/serving/vllm/README.md)
- [Distributed Inferencing on vLLM using Persistent disk](https://github.com/GoogleCloudPlatform/accelerated-platforms/blob/rueth-inferencing/use-cases/inferencing/serving/vllm/persistent-disk/README.md)
- [vLLM Metrics](https://github.com/GoogleCloudPlatform/accelerated-platforms/blob/rueth-inferencing/use-cases/inferencing/serving/vllm/metrics/README.md)
- [vLLM autoscaling with horizontal pod autoscaling (HPA)](https://github.com/GoogleCloudPlatform/accelerated-platforms/blob/rueth-inferencing/use-cases/inferencing/serving/vllm/autoscaling/README.md)
- [Benchmarking with …

Review updates

---

test/ci-cd/cloudbuild/uc-federated-learning-terraform-destroy.yaml
test/ci-cd/cloudbuild/uc-federated-learning-terraform.yaml
test/ci-cd/terraform/cloudbuild/cloudbuild_trigger.tf

Configure no-op cloud build triggers for the federated learning use case.

Federated learning use case CI/CD

---

README.md
docs/use-cases/federated-learning/README.md
platforms/gke/base/use-cases/federated-learning/README.md
test/ci-cd/cloudbuild/uc-federated-learning-terraform-destroy.yaml
test/ci-cd/cloudbuild/uc-federated-learning-terraform.yaml
test/ci-cd/terraform/cloudbuild/cloudbuild_trigger.tf

Added a placeholder and Cloud Build triggers for the federated learning use case.

Integrate the federated learning use case

---

README.md
platforms/gke-aiml/playground/README.md
test/scripts/helpers/playground_config.sh

- Add gradio/locust endpoints to README
- Remove mlflow cleanup duplication in test script

Additional endpoints for cleanup

---

platforms/gke-aiml/playground/gateway.tf

- fixing gateway.tf to help with clean platform build

fixing gateway

---

.gitignore
platforms/gke/base/use-cases/federated-learning/README.md
platforms/gke/base/use-cases/federated-learning/common.sh
platforms/gke/base/use-cases/federated-learning/deploy.sh
platforms/gke/base/use-cases/federated-learning/teardown.sh
platforms/gke/base/use-cases/federated-learning/terraform/initialize/main.tf
platforms/gke/base/use-cases/federated-learning/terraform/private_google_access/.terraform.lock.hcl
platforms/gke/base/use-cases/federated-learning/terraform/private_google_access/_cluster.auto.tfvars
platforms/gke/base/use-cases/federated-learning/terraform/private_google_access/_cluster_variables.tf
platforms/gke/base/use-cases/federated-learning/terraform/private_google_access/_networking.auto.tfvars
platforms/gke/base/use-cases/federated-learning/terraform/private_google_access/_networking_variables.tf
platforms/gke/base/use-cases/federated-learning/terraform/private_google_access/_platform.auto.tfvars
platforms/gke/base/use-cases/federated-learning/terraform/private_google_access/_platform_variables.tf
platforms/gke/base/use-cases/federated-learning/terraform/private_google_access/_uc_federated_learning.auto.tfvars
platforms/gke/base/use-cases/federated-learning/terraform/private_google_access/_uc_federated_learning_variables.tf
platforms/gke/base/use-cases/federated-learning/terraform/private_google_access/backend.tf
platforms/gke/base/use-cases/federated-learning/terraform/private_google_access/main.tf
platforms/gke/base/use-cases/federated-learning/terraform/private_google_access/project.tf
platforms/gke/base/use-cases/federated-learning/terraform/private_google_access/versions.tf
test/ci-cd/terraform/cloudbuild/cloudbuild_trigger.tf

Configure Private Google Access for the federated learning use case

feat(federated-learning): configure private google access

---

platforms/gke-aiml/playground/container_cluster.tf
platforms/gke/base/core/container_cluster/container_cluster.tf
terraform/modules/cluster/gke.tf

Enable Cost allocation for cluster config playground, core and modules

Enable cost allocation to cluster configurations

---

platforms/gke/base/use-cases/federated-learning/README.md
platforms/gke/base/use-cases/federated-learning/terraform/example_nvidia_flare_tff/templates/nvidia-flare-tff-example/nvidia_flare_tff_example_service_entries_server.yaml

- Add Cloud Storage APIs to Cloud Service Mesh entries
- Update README to add more troubleshooting information

fix: fix fl use case

---

platforms/gke/base/use-cases/inference-ref-arch/kubernetes-manifests/online-inference-gpu-h100-llama4-scout/set-h100-80gb-high-compute-class.yaml
platforms/gke/base/use-cases/inference-ref-arch/terraform/initialize/local_files.tf
test/ci-cd/cloudbuild/platforms/gke/base/use-cases/inference-ref-arch/scripts.yaml
test/ci-cd/container_images/dockerfile.runner

- Fix the Kustomize patch to set the custom compute class selector.
- Fix the IAM account name to grant access to the storage bucket where models were downloaded

fix: correctly set the compute class and iam

---

.github/workflows/dictionary/comfyui.txt
platforms/gke/base/use-cases/inference-ref-arch/examples/comfyui/README.md
platforms/gke/base/use-cases/inference-ref-arch/terraform/_shared_config/comfyui_variables.tf
platforms/gke/base/use-cases/inference-ref-arch/terraform/_shared_config/outputs.tf
platforms/gke/base/use-cases/inference-ref-arch/terraform/comfyui/copy_checkpoints/cloudbuild.yaml
platforms/gke/base/use-cases/inference-ref-arch/terraform/comfyui/gcs.tf
platforms/gke/base/use-cases/inference-ref-arch/terraform/comfyui/iam.tf
platforms/gke/base/use-cases/inference-ref-arch/terraform/comfyui/src/Dockerfile
platforms/gke/base/use-cases/inference-ref-arch/terraform/comfyui/templates/workloads/comfyui_nvidia-l4.tftpl.yaml
platforms/gke/base/use-cases/inference-ref-arch/terraform/comfyui/workload.tf

Fine tune ComfyUI deployment
fine tuning comfyui deployment
fine tune comfyui deployment
Fine tuning ComfyUI deployment

Fine tuning ComfyUI deployment

---

platforms/gke/base/_shared_config/outputs.tf
platforms/gke/base/_shared_config/scripts/configuration_from_gcs.sh
platforms/gke/base/_shared_config/scripts/configuration_to_gcs.sh
platforms/gke/base/core/huggingface/initialize/README.md

Primarily for use in Qwiklabs.

Added configuration to GCS scripts

---

platforms/gke/base/use-cases/federated-learning/terraform/network/.terraform.lock.hcl
platforms/gke/base/use-cases/federated-learning/terraform/secret_manager/.terraform.lock.hcl

This PR adds missing lock files

fix: add missing terraform lock files

---

.github/workflows/dictionary/shell.txt
platforms/gke/base/use-cases/inference-ref-arch/examples/online-inference-gpu/README.md
platforms/gke/base/use-cases/inference-ref-arch/examples/online-inference-tpu/README.md
platforms/gke/base/use-cases/inference-ref-arch/terraform/README.md

`nc` doesn't appear to be available in Cloud Shell by default, so switching to `telnet`

Changed nc to telnet

---

modules/python/src/custom_nodes/google_genmedia/virtual_try_on.py
platforms/gke/base/use-cases/inference-ref-arch/terraform/comfyui/src/comfyui-workflows/virtual-try-on.json

add watermark option to virtual try on

add watermark option  to virtual try on
